### ISSUE TITLE
Define snippets by a few sentences rather than 512 characters

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/covid19#5]
Rather than snippets for the answer being in 512 character chunks of the text (`text[text_i:text_i+512]` in predict), define snippets by a few sentences.

We found that sometimes the answer was found in a badly cut off sentence, e.g. "the most common route of viral transmission is through close contact with infectious secret" rather than "the most common route of viral transmission is through close contact with infectious secretions (sputum, serum, blood, and respiratory droplets) from a COVID-19 patient"

**Comment by nsorros** [comment]
Should we split by sentence or try to combine sentences as long as we keep below 512?

**Comment by lizgzil** [comment]
Could do chunks of 3 sentences? I was seeing that this was about the length of 512 characters
